#!/usr/bin/env bash
# Copyright 2022 Meta Mind AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


cd "$(dirname "$0")/.."

mkdir -p output

> output/sector-average-mapping.ts cat << EOL
/**
  Generated by:
  https://github.com/normative-io/smech-country-mapping/blob/develop/scripts/generate-sector-avg-mapping.sh

  List of country codes (excluding regions) in exiobase and a mapping of: ISO 3166-1 alpha-2 country codes <=> exio region codes
  to see available exio codes, look at:
  https://github.com/normative-io/smech-country-mapping/blob/develop/scripts/import.sql
**/

EOL

{
  echo '// Country codes in exiobase'
  echo 'export const knownCountries = ('
  sqlite3 data/mapping.db \
    "select json_group_array(alpha2) from knownalpha2 where level = 'country' order by alpha2;"
  echo ');'
  echo ''
  echo '// ISO 3166-1 alpha-2 country codes to exio region codes'
  echo 'export const countryMapping = '
  sqlite3 data/mapping.db \
    "SELECT json_group_object(alpha2, exiobase_region_code) FROM allcountries ORDER BY alpha2;"
  echo ';'
} >> output/sector-average-mapping.ts

npx prettier --print-width 120 --single-quote -w \
  output/sector-average-mapping.ts
